name: Release automation

on:
  push:
    branches:
      - main #-dont

jobs:
  build:

    name: Create Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '21.x'
      - name: npm install and build
        run: |
          npm install
          npm run build

      - name: ⚙️ Unzip dist files
        run: |
          rm -rf artifact
          mkdir artifact
          #unzip ${{ steps.pack.outputs.archive }} -d artifact
          ls -la

      - name: Read version infos
        id: version-infos
        uses: jaywcjlove/github-action-read-file@main
        with:
          branch: main
          path: release.ver
      - name: Read version changelog
        id: version-chl
        uses: jaywcjlove/github-action-read-file@main
        with:
          branch: main
          path: release.chl

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          #steps.ghpages.outputs.content
          tag_name: ${{ steps.version-infos.outputs.content }}
          release_name: Release ${{ steps.version-infos.outputs.content }}
          body: |
            Changes in this Release
            ${{ steps.version-chl.outputs.content }}
          draft: false
          prerelease: false
