name: Automation test

on:
  push:
    branches:
      - automations # Remove this line if your primary branch is "master"

jobs:
  build:

    name: Create Release
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: v0.0.1-release-tests.1 #${{ github.ref }}
          release_name: Release v0.0.1-release-tests.1 #${{ github.ref }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false
          
          
#      MUST BECOME PUBLISHING - building and UPLOADING IS USELESS
#      - name: Checkout repository
#        uses: actions/checkout@v4
#      - name: Use Node.js
#        uses: actions/setup-node@v3
#        with:
#          node-version: '21.x'
#      - name: npm install, build, and test
#        run: |
#          npm install
#          npm run build --if-present
#          npm test
#      - name: Archive production artifacts
#        uses: actions/upload-artifact@v3
#        with:
#          name: dist-without-markdown
#          path: |
#            dist
#            !dist/**/*.md
