name: Automation test

on:
  push:
    branches:
      - automations-dont # Remove this line if your primary branch is "master"

jobs:
  build:

    name: Create Release
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '21.x'
#  NOT NEEDED BY NOW
#      - name: npm install and build
#        run: |
#          npm install
#          npm run build
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: v0.0.1-release-tests.2 #${{ github.ref }}
          release_name: Release v0.0.1-release-tests.2 #${{ github.ref }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false
